version: '3.8'
services:
  driftsim:
    container_name: driftsim
    image: driftsim
    build: ./
    volumes:
      - ./results:/app/results
    command: python3 main.py ${args}

  driftsim_jupyter:
    container_name: driftsim_jupyter_${port}
    image: driftsim
    ports:
      - ${port}:8888
    volumes:
      - ./config/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
    command: jupyter notebook
